### ISSUE TITLE
Orders automation

### ISSUE THREAD

**Issue by arkadybabaev** [ababaev/alh#13]
It needs to add special button, which will analyse orders and according to next patterns will generate specific orders for units.
Also it should analyse existing orders to not duplicate it, if one was already added.
1) @;;automove X,Y,Z DIRECTION DIRECTION... 
If unit is in region X,Y,Z it should get order "MOVE DIRECTION DIRECTION..."

2) @;;automovetype WALK/RIDE/FLY
Should define minimal level of speed for the unit to move after operations

3) @;;autosource MASK A B ITEM
If unit is in the same region, as another unit (sourceunit), which name or number fit the MASK, unit will take some ITEM from sourceunit.
A -- described amount which have to be left at sourceunit. If A = 0, everything may be taken
B -- described amount of ITEM in sourceunit to take ITEM from it. If B = 0, any amount may be taken
For example:
@;;autosource 12345 500 1000 SILV
will mean, that if unit with number or name uncluding 12345 will have at least 1000 SILV, then it is possible to take SILV from it, leaving not less than 500 SILV
4) @;;autosupport MASK A B ITEM
If among regions listed in "automove" there are units fitting MASK then (targetunits), at moment, when unit is near any sourceunit, and targetunits has less ITEM than A, unit should try to take B amount of those items from unitsource for the targetunits.
If unit is near targetunit, and targetunit has less ITEM than A, unit should try to fill it to amount B.
A -- if targetunit has ITEM below A, demand should be formed. -1 means always demand
B -- expected amount of ITEMs at targetunit. -1 -- means as max as possible

**Comment by arkadybabaev** [comment]
This should be enough to be able to automate silver spreading over regions by caravans, caravans themselves and collection items

**Comment by ababaev** [comment]
Resolved
