### ISSUE TITLE
CMake does not generate proper config.h file and build is failing on Linux and Windows

### ISSUE THREAD

**Issue by valdisz** [ababaev/alh#24]
CMake does not generate proper config.h file and build is failing on Linux and Windows.

Actual build output could be seen here: https://github.com/valdisz/alh/runs/1317594882?check_suite_focus=true#step:10:933

Right now there are 2 problems with `config.h`:

1. It is not found (right now `config.h` is placed in the build directory, not in the source directory)
2. It is not what other files are expecting, I mean that other files, which are using `config.h`, are expecting different content comparing to what this file has.

**Comment by ababaev** [comment]
Resolved

**Comment by ababaev** [comment]
Resolved
